cmake_minimum_required(VERSION 3.22)
project(rapfiboard_native LANGUAGES C CXX)
set(NO_COMMAND_MODULES ON CACHE BOOL "" FORCE)
set(ENABLE_LTO OFF CACHE BOOL "" FORCE)
set(USE_SSE OFF CACHE BOOL "" FORCE)
set(USE_AVX2 OFF CACHE BOOL "" FORCE)
set(USE_AVX512 OFF CACHE BOOL "" FORCE)
set(USE_BMI2 OFF CACHE BOOL "" FORCE)
set(USE_VNNI OFF CACHE BOOL "" FORCE)
set(USE_NEON_DOTPROD OFF CACHE BOOL "" FORCE)
if(ANDROID_ABI STREQUAL "arm64-v8a")
    set(USE_NEON ON CACHE BOOL "" FORCE)
else()
    set(USE_NEON OFF CACHE BOOL "" FORCE)
endif()
add_subdirectory(../vendor/rapfi/Rapfi rapfi)
if(ANDROID)
    get_target_property(RAPFI_LIBS rapfi LINK_LIBRARIES)
    list(REMOVE_ITEM RAPFI_LIBS pthread)
    set_target_properties(rapfi PROPERTIES LINK_LIBRARIES "${RAPFI_LIBS}")
    set_target_properties(rapfi PROPERTIES OUTPUT_NAME "librapfi.so")
    target_link_options(rapfi PRIVATE "-Wl,-z,max-page-size=16384")
endif()
